services:
  - type: web
    name: src-form-discord
    runtime: python
    buildCommand: "apt-get install -y fonts-noto-cjk && pip install -r tools/requirements_form.txt"
    startCommand: "gunicorn --chdir tools form_discord_web:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: GOOGLE_TOKEN_B64
        sync: false
